// Code generated by protoc-gen-go.
// source: asnlookup.protos
// DO NOT EDIT!

/*
Package asnlookup is a generated protocol buffer package.

It is generated from these files:
	asnlookup.protos

It has these top-level messages:
	Empty
	HelloReply
	LookupRequest
	LookupReply
	LookupRequestBatch
	LookupReplyBatch
*/
package asnlookup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LookupRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *LookupRequest) Reset()                    { *m = LookupRequest{} }
func (m *LookupRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()               {}
func (*LookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LookupRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type LookupReply struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	As      int32  `protobuf:"varint,2,opt,name=as" json:"as,omitempty"`
	Prefix  string `protobuf:"bytes,3,opt,name=prefix" json:"prefix,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	Cc      string `protobuf:"bytes,5,opt,name=cc" json:"cc,omitempty"`
}

func (m *LookupReply) Reset()                    { *m = LookupReply{} }
func (m *LookupReply) String() string            { return proto.CompactTextString(m) }
func (*LookupReply) ProtoMessage()               {}
func (*LookupReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LookupReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LookupReply) GetAs() int32 {
	if m != nil {
		return m.As
	}
	return 0
}

func (m *LookupReply) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LookupReply) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LookupReply) GetCc() string {
	if m != nil {
		return m.Cc
	}
	return ""
}

type LookupRequestBatch struct {
	Requests []*LookupRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *LookupRequestBatch) Reset()                    { *m = LookupRequestBatch{} }
func (m *LookupRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*LookupRequestBatch) ProtoMessage()               {}
func (*LookupRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LookupRequestBatch) GetRequests() []*LookupRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type LookupReplyBatch struct {
	Replies []*LookupReply `protobuf:"bytes,1,rep,name=replies" json:"replies,omitempty"`
}

func (m *LookupReplyBatch) Reset()                    { *m = LookupReplyBatch{} }
func (m *LookupReplyBatch) String() string            { return proto.CompactTextString(m) }
func (*LookupReplyBatch) ProtoMessage()               {}
func (*LookupReplyBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LookupReplyBatch) GetReplies() []*LookupReply {
	if m != nil {
		return m.Replies
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "asnlookup.Empty")
	proto.RegisterType((*HelloReply)(nil), "asnlookup.HelloReply")
	proto.RegisterType((*LookupRequest)(nil), "asnlookup.LookupRequest")
	proto.RegisterType((*LookupReply)(nil), "asnlookup.LookupReply")
	proto.RegisterType((*LookupRequestBatch)(nil), "asnlookup.LookupRequestBatch")
	proto.RegisterType((*LookupReplyBatch)(nil), "asnlookup.LookupReplyBatch")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Asnlookup service

type AsnlookupClient interface {
	Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloReply, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error)
	LookupMany(ctx context.Context, opts ...grpc.CallOption) (Asnlookup_LookupManyClient, error)
	LookupBatch(ctx context.Context, in *LookupRequestBatch, opts ...grpc.CallOption) (*LookupReplyBatch, error)
}

type asnlookupClient struct {
	cc *grpc.ClientConn
}

func NewAsnlookupClient(cc *grpc.ClientConn) AsnlookupClient {
	return &asnlookupClient{cc}
}

func (c *asnlookupClient) Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/asnlookup.Asnlookup/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asnlookupClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error) {
	out := new(LookupReply)
	err := grpc.Invoke(ctx, "/asnlookup.Asnlookup/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asnlookupClient) LookupMany(ctx context.Context, opts ...grpc.CallOption) (Asnlookup_LookupManyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Asnlookup_serviceDesc.Streams[0], c.cc, "/asnlookup.Asnlookup/LookupMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &asnlookupLookupManyClient{stream}
	return x, nil
}

type Asnlookup_LookupManyClient interface {
	Send(*LookupRequest) error
	Recv() (*LookupReply, error)
	grpc.ClientStream
}

type asnlookupLookupManyClient struct {
	grpc.ClientStream
}

func (x *asnlookupLookupManyClient) Send(m *LookupRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *asnlookupLookupManyClient) Recv() (*LookupReply, error) {
	m := new(LookupReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *asnlookupClient) LookupBatch(ctx context.Context, in *LookupRequestBatch, opts ...grpc.CallOption) (*LookupReplyBatch, error) {
	out := new(LookupReplyBatch)
	err := grpc.Invoke(ctx, "/asnlookup.Asnlookup/LookupBatch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Asnlookup service

type AsnlookupServer interface {
	Hello(context.Context, *Empty) (*HelloReply, error)
	Lookup(context.Context, *LookupRequest) (*LookupReply, error)
	LookupMany(Asnlookup_LookupManyServer) error
	LookupBatch(context.Context, *LookupRequestBatch) (*LookupReplyBatch, error)
}

func RegisterAsnlookupServer(s *grpc.Server, srv AsnlookupServer) {
	s.RegisterService(&_Asnlookup_serviceDesc, srv)
}

func _Asnlookup_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsnlookupServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asnlookup.Asnlookup/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsnlookupServer).Hello(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asnlookup_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsnlookupServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asnlookup.Asnlookup/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsnlookupServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asnlookup_LookupMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AsnlookupServer).LookupMany(&asnlookupLookupManyServer{stream})
}

type Asnlookup_LookupManyServer interface {
	Send(*LookupReply) error
	Recv() (*LookupRequest, error)
	grpc.ServerStream
}

type asnlookupLookupManyServer struct {
	grpc.ServerStream
}

func (x *asnlookupLookupManyServer) Send(m *LookupReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *asnlookupLookupManyServer) Recv() (*LookupRequest, error) {
	m := new(LookupRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Asnlookup_LookupBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequestBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsnlookupServer).LookupBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asnlookup.Asnlookup/LookupBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsnlookupServer).LookupBatch(ctx, req.(*LookupRequestBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Asnlookup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "asnlookup.Asnlookup",
	HandlerType: (*AsnlookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Asnlookup_Hello_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Asnlookup_Lookup_Handler,
		},
		{
			MethodName: "LookupBatch",
			Handler:    _Asnlookup_LookupBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LookupMany",
			Handler:       _Asnlookup_LookupMany_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "asnlookup.protos",
}

func init() { proto.RegisterFile("asnlookup.protos", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0xd9, 0xc5, 0x05, 0x19, 0xa2, 0x21, 0x13, 0x25, 0x0d, 0xc6, 0x84, 0xf4, 0x60, 0xd6,
	0x0b, 0x21, 0xe8, 0xd1, 0x8b, 0x06, 0x13, 0xe3, 0x9f, 0x4b, 0xdf, 0xa0, 0x2e, 0x55, 0x89, 0x85,
	0xd6, 0x76, 0x89, 0xee, 0x5b, 0xf8, 0xc8, 0x86, 0x96, 0xc2, 0x92, 0xec, 0x5e, 0x3c, 0x7e, 0xdf,
	0x7c, 0xf3, 0xdb, 0xd9, 0x99, 0x42, 0x8f, 0xdb, 0xa5, 0x54, 0xea, 0x73, 0xa5, 0x47, 0xda, 0xa8,
	0x5c, 0x59, 0xec, 0x6c, 0x1d, 0xda, 0x86, 0xe4, 0x7e, 0xa1, 0xf3, 0x82, 0x5e, 0x00, 0x3c, 0x08,
	0x29, 0x15, 0x13, 0x5a, 0x16, 0x48, 0xa0, 0xbd, 0x10, 0xd6, 0xf2, 0x77, 0x41, 0xa2, 0x61, 0x94,
	0x76, 0x58, 0x90, 0xf4, 0x12, 0x8e, 0x9e, 0x5d, 0x2b, 0x13, 0x5f, 0x2b, 0x61, 0xf3, 0x75, 0x94,
	0xcf, 0x66, 0x46, 0x58, 0x1b, 0xa2, 0x1b, 0x49, 0x57, 0xd0, 0x0d, 0xd1, 0x0d, 0xb3, 0x3a, 0x88,
	0xc7, 0x10, 0x73, 0x4b, 0xe2, 0x61, 0x94, 0x26, 0x2c, 0xe6, 0x16, 0xfb, 0xd0, 0xd2, 0x46, 0xbc,
	0xcd, 0x7f, 0x48, 0xd3, 0x05, 0x37, 0x0a, 0x4f, 0x20, 0x51, 0xdf, 0x4b, 0x61, 0xc8, 0x81, 0xb3,
	0xbd, 0x58, 0x77, 0x67, 0x19, 0x49, 0x9c, 0x15, 0x67, 0x19, 0x7d, 0x04, 0xdc, 0x9b, 0xf0, 0x8e,
	0xe7, 0xd9, 0x07, 0x5e, 0xc3, 0xa1, 0xf1, 0x7a, 0xfd, 0xf9, 0x66, 0xda, 0x9d, 0x90, 0xd1, 0x6e,
	0x31, 0x7b, 0x0d, 0x6c, 0x9b, 0xa4, 0x53, 0xe8, 0x95, 0x7e, 0xc1, 0x93, 0xc6, 0xd0, 0x36, 0x42,
	0xcb, 0xb9, 0x08, 0xa0, 0x7e, 0x05, 0x48, 0xcb, 0x82, 0x85, 0xd8, 0xe4, 0x37, 0x86, 0xce, 0x6d,
	0x88, 0xe0, 0x04, 0x12, 0xb7, 0x69, 0xec, 0x95, 0xfa, 0xdc, 0x11, 0x06, 0xa7, 0x25, 0x67, 0x77,
	0x0d, 0xda, 0xc0, 0x1b, 0x68, 0x79, 0x32, 0xd6, 0x4e, 0x3d, 0xa8, 0x19, 0x83, 0x36, 0x70, 0x0a,
	0xe0, 0x8d, 0x17, 0xbe, 0x2c, 0xfe, 0x43, 0x48, 0xa3, 0x71, 0x84, 0x4f, 0xe1, 0x9c, 0x7e, 0x0d,
	0xe7, 0x75, 0x18, 0x57, 0x1e, 0x9c, 0x55, 0xb3, 0x5c, 0x91, 0x36, 0x5e, 0x5b, 0xee, 0x29, 0x5e,
	0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x05, 0x15, 0xa5, 0x84, 0x9d, 0x02, 0x00, 0x00,
}
